config/routes.rb
Rails.application.routes.draw do

#=============================================================================
# ================================ USER ======================================
#=============================================================================

  namespace :user do

    controller :users do
    end
    resources :users

    controller :servicos do
    end
    resources :servicos

    controller :contatos do
    end
    resources :contatos

    controller :metas do
    end
    resources :metas

    controller :submetas do
    end
    resources :submetas

    controller :events do
    end
    resources :events

    controller :configuracoes do
      get '/configuracoes/gerais' => :gerais, as: :configuracoes_gerais
      get '/configuracoes/visualizar_home' => :visualizar_home, as: :configuracoes_visualizar_home
      post '/configuracoes/gerais_salvar' => :gerais_salvar, as: :configuracoes_gerais_salvar
    end

    controller :pages do
        get '/home' => :home
    end
    root 'pages#home'
  end

#=============================================================================
# ================================ PÚBLICO ===================================
#=============================================================================

  devise_for :users, :controllers => { registrations: 'registrations'}


  authenticated :user do
    root 'user/pages#home', as: :authenticated_root
  end

  controller :users do
  end
  resources :users

  controller :contatos do
  end
  resources :contatos

  controller :pages do
    get '/home' => :home
    get '/login' => :login

  end 

  root 'pages#home'


get '*path' => redirect('/')
end

app/controllers/user/arquivos_controller.rb
class User::ArquivosController < User::UserController

  before_action :set_arquivo, only: [:show, :edit, :update, :destroy]

  # GET /arquivos
  def index
    conditions = []
    conditions << "arquivos.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(arquivos.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @arquivos = Arquivo.where(conditions.join(' AND ')).order("arquivos.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /arquivos/1
  def show
  end

  def new
    @arquivo = Arquivo.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update

    if @arquivo.update(arquivo_params)

      unless params[:arquivo][:categorias].blank?
        params[:arquivo][:categorias] = params[:arquivo][:categorias]-[""]
        categorias = Categoria.where("categorias.id IN (#{params[:arquivo][:categorias].split(/\W+/).uniq.join(', ')})") 
      end
      unless categorias.blank?
        categorias.each do |categoria|
          @arquivo.categorias << categoria unless @arquivo.categorias.include?categoria
        end
      end

    end



    respond_to do |format|

      format.js
    end
  end

  def create

    @arquivo = Arquivo.new(arquivo_params)
    

    unless params[:arquivo][:categorias].blank?
      params[:arquivo][:categorias] = params[:arquivo][:categorias]-[""]
      categorias = Categoria.where("categorias.id IN (#{params[:arquivo][:categorias].split(/\W+/).uniq.join(', ')})") unless params[:arquivo][:categorias].blank?
    end

    respond_to do |format|

      if @arquivo.save
        unless categorias.blank?
          categorias.each do |categoria|
            @arquivo.categorias << categoria unless @arquivo.categorias.include?categoria
          end
        end
      end
      format.js
    end
  end

  def destroy
    @arquivo.destroy
    
    redirect_to request.referrer, notice: "Arquivo Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arquivo
      @arquivo = Arquivo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def arquivo_params
      params.require(:arquivo).permit(:nome, :descricao, :observacao, {arquivos: []},
                                    itens_attributes: [:id, :arquivo, :thumb, :_destroy])
    end


end

app/controllers/user/categorias_controller.rb
class User::CategoriasController < User::UserController

  before_action :set_categoria, only: [:show, :edit, :update]
  before_action :garantir_autorizacao

  # GET /categorias
  def index
    conditions = []
    conditions << "categorias.id = #{params[:id]}" unless params[:id].blank?

    @categorias = Categoria.where(conditions.join(' AND '))

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /categorias/1
  def show
  end

  def new
    @categoria = Categoria.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update
      if @categoria.update(categoria_params)
        redirect_to request.referrer, notice: "Categoria atualizada!"
      else
        render :edit
      end
  end

  def create
    @categoria = Categoria.new(categoria_params)

    @categoria.save
    respond_to do |format|

      @categoria.save
      format.js
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def categoria_params
      params.require(:categoria).permit(:nome, :descricao, :ativo)
    end



    def garantir_autorizacao
      authorize! :config,     :categorias
    end


end

app/controllers/user/configuracoes_controller.rb
class User::ConfiguracoesController < User::UserController

  def gerais
  end

  def visualizar_home
    @servicos = Servico.all
    @contato = Contato.new
  end

  def gerais_salvar
  	#SEO
    Setting['CONFIGURACOES.site']                           		= params[:site]
    Setting['CONFIGURACOES.title']                           		= params[:title]
    Setting['CONFIGURACOES.descricao']                           	= params[:descricao]
    Setting['CONFIGURACOES.keys']    								= params[:keys]	
  	#Informações
    Setting['CONFIGURACOES.email']    								= params[:email]	
    Setting['CONFIGURACOES.telefone']    								= params[:telefone]	
    Setting['CONFIGURACOES.site_link']    								= params[:site_link]	
    Setting['CONFIGURACOES.facebook']    								= params[:facebook]	
    
  	#sobre
    Setting['YATAH.mensagem']                             = params[:mensagem]
    Setting['YATAH.titulo']                             = params[:titulo]
    Setting['YATAH.conteudo']                             = params[:conteudo]
    Setting['YATAH.titulo_portfolio']                             = params[:titulo_portfolio]
    Setting['YATAH.subtitulo_portfolio']                             = params[:subtitulo_portfolio]
    Setting['YATAH.o_que_fazemos']                             = params[:o_que_fazemos]
    Setting['YATAH.servicos']                             = params[:servicos]
    Setting['YATAH.contato_titulo']                             = params[:contato_titulo]
    Setting['YATAH.contato_conteudo']                             = params[:contato_conteudo]



    Setting['YATAH.font_mensagem']                             = params[:font_mensagem]
    Setting['YATAH.font_size']                             = params[:font_size]
    Setting['YATAH.position']                             = params[:position]
    Setting['YATAH.font_titulo']                             = params[:font_titulo]
    Setting['YATAH.font_titulo_portfolio']                             = params[:font_titulo_portfolio]
    Setting['YATAH.font_subtitulo_portfolio']                             = params[:font_subtitulo_portfolio]
    Setting['YATAH.font_o_que_fazemos']                             = params[:font_o_que_fazemos]
    Setting['YATAH.font_servicos']                             = params[:font_servicos]
    Setting['YATAH.font_contato_titulo']                             = params[:font_contato_titulo]





    respond_to do |format|
      format.js {render inline: "Materialize.toast('Atualizado', 4000, 'green')" }
    end

  end
end

app/controllers/user/contatos_controller.rb
class User::ContatosController < User::UserController

  before_action :set_contato, only: [:show, :edit, :update, :destroy]
  before_action :garantir_autorizacao

  # GET /contatos
  def index
    conditions = []
    conditions << "contatos.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(contatos.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @contatos = Contato.where(conditions.join(' AND ')).order("contatos.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos/1
  def show
  end

  def new
    @contato = Contato.new
  end

  def edit
  end

  # PATCH/PUT /contatos/1
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.js {render inline: "Materialize.toast('Atualizado com sucesso!', 4000, 'green')" }
      else
        format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
      end
    end
  end

  def create
    @contato = Contato.new(contato_params)
      if @contato.save
        redirect_to edit_user_contato_path(@contato), notice: "Contato Criado!"
      else
        respond_to do |format|
            format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
        end
      end
  end

  def destroy
    @contato.destroy
    
    redirect_to request.referrer, notice: "Contato Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contato_params
      params.require(:contato).permit(:empresa, :plano_id, :nome, :email, :celular, :mensagem)
    end

    def garantir_autorizacao
      authorize! :config,     :contatos
    end

end

app/controllers/user/emails_controller.rb
class User::EmailsController < User::UserController

  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  def index
    conditions = []
    conditions << "emails.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(emails.conteudo) LIKE '%#{params[:conteudo]}%') OR (UPPER(emails.descricao) LIKE '%#{params[:conteudo]}%')" unless params[:conteudo].blank?

    @emails = Email.where(conditions.join(' AND ')).order("emails.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /emails/1
  def show
  end

  def new
    @email = Email.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update
      redirect_to request.referrer, notice: "Não é possível editar uma email já enviado!"
  end

  def create
  	@email = Email.new(email_params)

  	if @email.save
      Contato.where("contatos.email IS NOT NULL").each do |contato|
        SendMailer.delay.enviar_email(contato, @email.conteudo)
      end
      redirect_to request.referrer, notice: "Email Criado!"
    else
  		redirect_to request.referrer, notice: "Não foi possível enviar!"
  	end
  end

  def destroy
    @email.destroy
    
    redirect_to request.referrer, notice: "Email Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def email_params
      params.require(:email).permit(:conteudo)
    end


end

app/controllers/user/events_controller.rb
class User::EventsController < User::UserController

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end]).where(user_id: current_user.id)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color, :user_id, :description)
    end
end

app/controllers/user/metas_controller.rb
class User::MetasController < User::UserController

  before_action :set_meta, only: [:show, :edit, :update, :destroy]
  before_action :garantir_autorizacao

  # GET /metas
  def index
    conditions = []
    conditions << "metas.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(metas.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @metas = Meta.where(conditions.join(' AND ')).order("metas.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /metas/1
  def show
  end

  def new
    @meta = Meta.new
  end

  def edit
  end

  # PATCH/PUT /metas/1
  def update
    respond_to do |format|
      if @meta.update(meta_params)

        @meta.submetas.destroy_all
        c = (@meta.data_inicio.to_date..@meta.data_fim.to_date).map{ |e| e.strftime("%d/%m/%Y")  }
        c.each do |data|
           submeta = Submeta.create(meta_id: @meta.id, data: "#{data}", flg_horas: ((@meta.horas.blank? or @meta.horas.to_i.zero?) ? false : true), horas: @meta.horas, descricao: @meta.descricao )  
           Event.create(title: "#{@meta.horas} #{'horas -' if submeta.flg_horas} #{@meta.nome} - #{@meta.porcentagem}%", color: "red", start: (submeta.data.to_date), end: (submeta.data.to_date+1.day), user_id: current_user.id, submeta_id: submeta.id, description: @meta.descricao)
           submeta = nil   
        end

        format.js {render inline: "Materialize.toast('Atualizado com sucesso!', 4000, 'green')" }
      else
        format.js
      end
    end
  end

  def create
    @meta = Meta.new(meta_params)

      if @meta.save
        c = (@meta.data_inicio.to_date..@meta.data_fim.to_date).map{ |e| e.strftime("%d/%m/%Y")  }
        c.each do |data|
           submeta = Submeta.create(meta_id: @meta.id, data: "#{data}", flg_horas: ((@meta.horas.blank? or @meta.horas.to_i.zero?) ? false : true), horas: @meta.horas, descricao: @meta.descricao )     
           Event.create(title: "#{@meta.horas} horas - #{@meta.nome} - #{@meta.porcentagem}%", color: "red", start: (submeta.data.to_date), end: (submeta.data.to_date+1.day), user_id: current_user.id, submeta_id: submeta.id, description: @meta.descricao)
           submeta = nil
        end
        redirect_to edit_user_meta_path(@meta), notice: "Meta Criado!"
      else
        respond_to do |format|
            format.js
        end
      end
  end

  def destroy
    @meta.destroy
    
    redirect_to request.referrer, notice: "Meta Deletada!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meta
      @meta = Meta.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def meta_params
      params.require(:meta).permit(:nome, :descricao, :publico, :data_inicio, :data_fim, :horas, :user_id )
    end

    def garantir_autorizacao
      authorize! :config,     :metas
    end

end

app/controllers/user/pages_controller.rb
class User::PagesController < User::UserController
  def home
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :image)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :current_password, :image)
  end
end

app/controllers/user/servicos_controller.rb
class User::ServicosController < User::UserController

  before_action :set_servico, only: [:show, :edit, :update, :destroy]
  before_action :garantir_autorizacao

  # GET /servicos
  def index
    conditions = []
    conditions << "servicos.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(servicos.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @servicos = Servico.where(conditions.join(' AND ')).order("servicos.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /servicos/1
  def show
  end

  def new
    @servico = Servico.new
  end

  def edit
  end

  # PATCH/PUT /servicos/1
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.js {render inline: "Materialize.toast('Atualizado com sucesso!', 4000, 'green')" }
      else
        format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
      end
    end
  end

  def create
    @servico = Servico.new(servico_params)
      if @servico.save
        redirect_to edit_user_servico_path(@servico), notice: "Serviço Criado!"
      else
        respond_to do |format|
            format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
        end
      end
  end

  def destroy
    @servico.destroy
    
    redirect_to request.referrer, notice: "Serviço Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def servico_params
      params.require(:servico).permit(:nome, :descricao, :icon, :icon_color, :icon_size)
    end

    def garantir_autorizacao
      authorize! :config,     :servicos
    end

end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
	
  before_action :authenticate_user!
  
  layout 'user'

  def home
  end

  
end

app/controllers/users_controller.rb
class UsersController < PublicController
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/metas/_form.html.erb
      <%= form_for [:user, @meta], remote: true do |f| %>

      <div id="form_error">
      </div>

      <div class="row">
        <div class="field">
          <div class="input-field col s12 m12 l12">
            <% if @meta.new_record? %>
              <%= f.text_field :user_id, type: "hidden", value: current_user.id %>
            <% end %>
          </div>
        </div>
        <div class="field">
          <div class="input-field col s12 m12 l12">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :user, value: "#{current_user.nome} - #{(l DateTime.now, format: :long)}", :readonly => true %>
            <label for="icon_prefix">Responsável</label>
          </div>
        </div>
        <div class="field">
          <div class="input-field col s12 m12 l12">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :nome %>
            <label for="icon_prefix">Nome da Meta (identificação)</label>
          </div>
        </div>
        <div class="field">
          <span style="font-style: italic; color: #777; margin-left: 10px;">Descrição do que será realizado</span>
          <div class="input-field col s12 m12">
            <%= f.cktext_area :descricao, ckeditor: {language: 'pt'} %>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :data_inicio, :onkeypress => "mascara(this, checaData)", maxlength: 10 %>
            <label for="icon_prefix">Data de Início</label>
          </div>
        </div>
        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :data_fim, :onkeypress => "mascara(this, checaData)", maxlength: 10 %>
            <label for="icon_prefix">Data de Término</label>
          </div>
        </div>
        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :horas, placeholder: "somente se horas for necessário no cumprimento da meta" %>
            <label for="icon_prefix">Horas</label>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="switch col s12">
          <div class="title">
            <span style="color: #666; font-size: 14px; margin: 0px;">Público</span>
          </div>
          <label>
            Não
            <%= f.check_box :publico %>
            <span class="lever"></span>
            Sim
          </label>
        </div>
      </div>


      
      <div class="row">
        <div class="input-field col s12">
          <div class="actions">
            <button class="btn blue waves-effect waves-light right" type="submit" name="action">Salvar
              <i class="material-icons right">send</i>
            </button>
          </div>
        </div>
      </div>

      <% end %>


    <% unless @meta.new_record? and @meta.submetas.blank? %>
      <br><br>
      <div class="layout">
          <h5 class="orange-text">Submetas</h5>
          <% @meta.submetas.each do |submeta| %>
            <div class="layout">
                <% if submeta.finalizado %>
                  <i class="material-icons green-text">check_circle</i>
                  <span style="font-size: 12px; font-style: italic; color: #777; ">Concluído</span>
                <% else %>
                  <i class="material-icons red-text">close</i>
                  <span style="font-size: 12px; font-style: italic; color: #777; ">Não concluído</span>
                <% end %>
              <br>
              <span class="blue-text">
                <%= (l submeta.data.to_date, format: :long) %>
              </span>
            </div>
          <% end %>
      </div>
    <% end %>
<style type="text/css">

  .item_meta{
    min-height: 100px;
    text-align: center;
    padding: 15px;
    border: 1px dashed #eee;
    span.nome{
      font-weight: 600;
    }
    span.descricao{
      line-height: 1.5;
    }
  }
</style>

<script type="text/javascript">

  $(document).ready(function() {
    $('select').material_select();
  });
    
</script>

app/views/user/metas/_list.html.erb
<table class="highlight responsive-table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Status</th>
      <th>Submetas</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @metas.each do |meta| %>
      <tr>
        <td>
          <span style="padding: 10px; border: 1px solid #2196f3; border-radius: 30px;">
            <%= meta.id %>
          </span>
        </td>
        <td>
          <%= meta.nome %><br>
          <span style="font-size: 10px; color: #777; font-style: italic;">(<%= l meta.created_at.to_date, format: :short %>)</span>
        </td> 
        <td><%= meta.status %></td>
        <td>
          <span class="blue-text" style="font-size: 18px; font-weight: 600;">
            <% if meta.horas.blank? or meta.horas.to_i.zero? %>
              <%= "#{meta.submetas.size}/#{meta.submetas.where(finalizado: true).size}" %>
            <% else %>
              <%= "#{meta.submetas.size*meta.horas.to_i}hrs / #{meta.horas_concluidas}hrs" %> 
            <% end %>
          </span>
        </td>
        <td>
          <%= link_to "<i class='material-icons'>search</i>".html_safe, user_meta_path(meta), class: "btn orange btn-floating" %>
          <%= link_to "<i class='material-icons'>edit</i>".html_safe, edit_user_meta_path(meta), class: "btn blue btn-floating" %>
          <%= link_to "<i class='material-icons'>delete</i>".html_safe, user_meta_path(meta), method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-floating", style: "background-color: red;" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/metas/create.js.erb
<% if @meta.errors.any? %>
  $("#form_error").html("<%= j( render '/shared/form_error', object: @meta )%>");
  $('html, body').animate({ scrollTop: 0 }, 'slow');
	Materialize.toast('Falha', 4000, 'red')
<% end %>

app/views/user/metas/edit.html.erb
<div id="user" class="container-fluid">
  <h4 class="title grey-text" style="margin: 0;" ><%= "Editar #{@meta.nome}" %></h4><br>
  <div class="layout">
	  <%= render 'form'  %>
  </div>
</div>

app/views/user/metas/index.html.erb
<div  style="border: 1px solid #ccc; padding: 15px;">
	<h4 class="title grey-text" style="margin: 0;" ><%= "METAS" %></h4>
  <br>
	<%= link_to "CRIAR META", new_user_meta_path, class: "btn green" %>
	

  <div class="row">
    <form class="col s12">
      <div class="row">
		<div class="input-field col s6 m6 l3">
		  <input id="id" type="text" class="validate">
		  <label class="active" for="id">Código</label>
		</div>
		<div class="input-field col s6 m6 l3">
		  <input id="name" type="text" class="validate">
		  <label class="active" for="name">Nome</label>
		</div>
		<div class="input-field col s6 m6 l3">
		<a id="buscar" class="btn blue">Buscar</a>
		</div>
      </div>
    </form>
  </div>

<div class="row">
  <div class="col s12 m12 l12">
    <div id="meta_list">
      <%= render 'list' %>
    </div>
  </div>
</div>

</div>

<script type="text/javascript">

  $(function($) {

    $("#buscar").click(function() {
      if( $(this).prop('value') != "" ) {
        var id = $("#id").prop('value');
        var name = $("#name").prop('value');
        att_index(id, name);
      }
    });
  });



</script>

<script type="text/javascript">
  
function att_index(id, name){

    $.ajax({
      url: "/user/users",
      method: "GET",
      dataType: "script",
      data: {
      	'id': 			id,
        'nome': 		name
      },
    });

}
</script>

<script type="text/javascript">
  $("input").keyup(function() {
    $(this).val($(this).val().toUpperCase());
  });
</script>

app/views/user/metas/index.js.erb
$("#meta_list").html("<%= j( render 'list' )%>");

app/views/user/metas/new.html.erb
<div id="user" class="container-fluid">
  <h4 class="grey-text" style="margin: 0;" ><%= "Nova Meta" %></h4>
  <br>
  <div class="layout">
	  <%= render 'form'  %>
  </div>
</div>

app/views/user/metas/show.html.erb
<div class="layout">
  <h5 class="blue-text"><%= @meta.nome %></h5>
  <br>
  <div class="layout">
    <span class="orange-text" style="font-size: 18px;">Descrição</span>
    <%= "#{@meta.descricao}".html_safe %>
  </div>
  <br>
  <% @meta.submetas.order(:data).each do |submeta| %>
    <div class="layout">
      <span style="padding: 5px; border: 1px solid #2196f3; color: #2196f3;"><%= submeta.meta.porcentagem %>%</span><br><br>
      <% unless submeta.horas.blank? or submeta.horas.to_i.zero? %>
        <span><%= "#{submeta.horas}hrs / #{submeta.horas_finalizadas.to_i}hrs" %></span><br>
      <% end %>
        <% if submeta.finalizado %>
          <i class="material-icons green-text">check_circle</i>
          <span style="font-size: 12px; font-style: italic; color: #777; ">Concluído - <%= submeta.user.nome unless submeta.user.blank? %></span>
        <% else %>
          <i class="material-icons red-text">close</i>
          <span style="font-size: 12px; font-style: italic; color: #777; ">Não concluído</span>
        <% end %>
        <br>
        <span class="blue-text">
          <%= (l submeta.data.to_date, format: :long) %>
        </span>
    </div>
  <% end %>
</div>

app/views/user/metas/update.js.erb
<% if @meta.errors.any? %>
  $("#form_error").html("<%= j( render '/shared/form_error', object: @meta )%>");
  $('html, body').animate({ scrollTop: 0 }, 'slow');
Materialize.toast('Falha', 4000, 'red')
<% end %>