config/routes.rb
Rails.application.routes.draw do

#=============================================================================
# ================================ USER ======================================
#=============================================================================

  namespace :user do

    controller :users do
    end
    resources :users

    controller :servicos do
    end
    resources :servicos

    controller :contatos do
    end
    resources :contatos

    controller :metas do
    end
    resources :metas

    controller :submetas do
    end
    resources :submetas

    controller :events do
    end
    resources :events

    controller :configuracoes do
      get '/configuracoes/gerais' => :gerais, as: :configuracoes_gerais
      get '/configuracoes/visualizar_home' => :visualizar_home, as: :configuracoes_visualizar_home
      post '/configuracoes/gerais_salvar' => :gerais_salvar, as: :configuracoes_gerais_salvar
    end

    controller :pages do
        get '/home' => :home
    end
    root 'pages#home'
  end

#=============================================================================
# ================================ PÚBLICO ===================================
#=============================================================================

  devise_for :users, :controllers => { registrations: 'registrations'}


  authenticated :user do
    root 'user/pages#home', as: :authenticated_root
  end

  controller :users do
  end
  resources :users

  controller :contatos do
  end
  resources :contatos

  controller :pages do
    get '/home' => :home
    get '/login' => :login

  end 

  root 'pages#home'


get '*path' => redirect('/')
end

app/controllers/user/arquivos_controller.rb
class User::ArquivosController < User::UserController

  before_action :set_arquivo, only: [:show, :edit, :update, :destroy]

  # GET /arquivos
  def index
    conditions = []
    conditions << "arquivos.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(arquivos.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @arquivos = Arquivo.where(conditions.join(' AND ')).order("arquivos.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /arquivos/1
  def show
  end

  def new
    @arquivo = Arquivo.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update

    if @arquivo.update(arquivo_params)

      unless params[:arquivo][:categorias].blank?
        params[:arquivo][:categorias] = params[:arquivo][:categorias]-[""]
        categorias = Categoria.where("categorias.id IN (#{params[:arquivo][:categorias].split(/\W+/).uniq.join(', ')})") 
      end
      unless categorias.blank?
        categorias.each do |categoria|
          @arquivo.categorias << categoria unless @arquivo.categorias.include?categoria
        end
      end

    end



    respond_to do |format|

      format.js
    end
  end

  def create

    @arquivo = Arquivo.new(arquivo_params)
    

    unless params[:arquivo][:categorias].blank?
      params[:arquivo][:categorias] = params[:arquivo][:categorias]-[""]
      categorias = Categoria.where("categorias.id IN (#{params[:arquivo][:categorias].split(/\W+/).uniq.join(', ')})") unless params[:arquivo][:categorias].blank?
    end

    respond_to do |format|

      if @arquivo.save
        unless categorias.blank?
          categorias.each do |categoria|
            @arquivo.categorias << categoria unless @arquivo.categorias.include?categoria
          end
        end
      end
      format.js
    end
  end

  def destroy
    @arquivo.destroy
    
    redirect_to request.referrer, notice: "Arquivo Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arquivo
      @arquivo = Arquivo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def arquivo_params
      params.require(:arquivo).permit(:nome, :descricao, :observacao, {arquivos: []},
                                    itens_attributes: [:id, :arquivo, :thumb, :_destroy])
    end


end

app/controllers/user/categorias_controller.rb
class User::CategoriasController < User::UserController

  before_action :set_categoria, only: [:show, :edit, :update]
  before_action :garantir_autorizacao

  # GET /categorias
  def index
    conditions = []
    conditions << "categorias.id = #{params[:id]}" unless params[:id].blank?

    @categorias = Categoria.where(conditions.join(' AND '))

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /categorias/1
  def show
  end

  def new
    @categoria = Categoria.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update
      if @categoria.update(categoria_params)
        redirect_to request.referrer, notice: "Categoria atualizada!"
      else
        render :edit
      end
  end

  def create
    @categoria = Categoria.new(categoria_params)

    @categoria.save
    respond_to do |format|

      @categoria.save
      format.js
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def categoria_params
      params.require(:categoria).permit(:nome, :descricao, :ativo)
    end



    def garantir_autorizacao
      authorize! :config,     :categorias
    end


end

app/controllers/user/configuracoes_controller.rb
class User::ConfiguracoesController < User::UserController

  def gerais
  end

  def visualizar_home
    @servicos = Servico.all
    @contato = Contato.new
  end

  def gerais_salvar
  	#SEO
    Setting['CONFIGURACOES.site']                           		= params[:site]
    Setting['CONFIGURACOES.title']                           		= params[:title]
    Setting['CONFIGURACOES.descricao']                           	= params[:descricao]
    Setting['CONFIGURACOES.keys']    								= params[:keys]	
  	#Informações
    Setting['CONFIGURACOES.email']    								= params[:email]	
    Setting['CONFIGURACOES.telefone']    								= params[:telefone]	
    Setting['CONFIGURACOES.site_link']    								= params[:site_link]	
    Setting['CONFIGURACOES.facebook']    								= params[:facebook]	
    
  	#sobre
    Setting['YATAH.mensagem']                             = params[:mensagem]
    Setting['YATAH.titulo']                             = params[:titulo]
    Setting['YATAH.conteudo']                             = params[:conteudo]
    Setting['YATAH.titulo_portfolio']                             = params[:titulo_portfolio]
    Setting['YATAH.subtitulo_portfolio']                             = params[:subtitulo_portfolio]
    Setting['YATAH.o_que_fazemos']                             = params[:o_que_fazemos]
    Setting['YATAH.servicos']                             = params[:servicos]
    Setting['YATAH.contato_titulo']                             = params[:contato_titulo]
    Setting['YATAH.contato_conteudo']                             = params[:contato_conteudo]



    Setting['YATAH.font_mensagem']                             = params[:font_mensagem]
    Setting['YATAH.font_size']                             = params[:font_size]
    Setting['YATAH.position']                             = params[:position]
    Setting['YATAH.font_titulo']                             = params[:font_titulo]
    Setting['YATAH.font_titulo_portfolio']                             = params[:font_titulo_portfolio]
    Setting['YATAH.font_subtitulo_portfolio']                             = params[:font_subtitulo_portfolio]
    Setting['YATAH.font_o_que_fazemos']                             = params[:font_o_que_fazemos]
    Setting['YATAH.font_servicos']                             = params[:font_servicos]
    Setting['YATAH.font_contato_titulo']                             = params[:font_contato_titulo]





    respond_to do |format|
      format.js {render inline: "Materialize.toast('Atualizado', 4000, 'green')" }
    end

  end
end

app/controllers/user/contatos_controller.rb
class User::ContatosController < User::UserController

  before_action :set_contato, only: [:show, :edit, :update, :destroy]
  before_action :garantir_autorizacao

  # GET /contatos
  def index
    conditions = []
    conditions << "contatos.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(contatos.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @contatos = Contato.where(conditions.join(' AND ')).order("contatos.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /contatos/1
  def show
  end

  def new
    @contato = Contato.new
  end

  def edit
  end

  # PATCH/PUT /contatos/1
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.js {render inline: "Materialize.toast('Atualizado com sucesso!', 4000, 'green')" }
      else
        format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
      end
    end
  end

  def create
    @contato = Contato.new(contato_params)
      if @contato.save
        redirect_to edit_user_contato_path(@contato), notice: "Contato Criado!"
      else
        respond_to do |format|
            format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
        end
      end
  end

  def destroy
    @contato.destroy
    
    redirect_to request.referrer, notice: "Contato Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def contato_params
      params.require(:contato).permit(:empresa, :plano_id, :nome, :email, :celular, :mensagem)
    end

    def garantir_autorizacao
      authorize! :config,     :contatos
    end

end

app/controllers/user/emails_controller.rb
class User::EmailsController < User::UserController

  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  def index
    conditions = []
    conditions << "emails.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(emails.conteudo) LIKE '%#{params[:conteudo]}%') OR (UPPER(emails.descricao) LIKE '%#{params[:conteudo]}%')" unless params[:conteudo].blank?

    @emails = Email.where(conditions.join(' AND ')).order("emails.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /emails/1
  def show
  end

  def new
    @email = Email.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update
      redirect_to request.referrer, notice: "Não é possível editar uma email já enviado!"
  end

  def create
  	@email = Email.new(email_params)

  	if @email.save
      Contato.where("contatos.email IS NOT NULL").each do |contato|
        SendMailer.delay.enviar_email(contato, @email.conteudo)
      end
      redirect_to request.referrer, notice: "Email Criado!"
    else
  		redirect_to request.referrer, notice: "Não foi possível enviar!"
  	end
  end

  def destroy
    @email.destroy
    
    redirect_to request.referrer, notice: "Email Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def email_params
      params.require(:email).permit(:conteudo)
    end


end

app/controllers/user/events_controller.rb
class User::EventsController < User::UserController

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end]).where(user_id: current_user.id)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color, :user_id, :description)
    end
end

app/controllers/user/metas_controller.rb
class User::MetasController < User::UserController

  before_action :set_meta, only: [:show, :edit, :update, :destroy]
  before_action :garantir_autorizacao

  # GET /metas
  def index
    conditions = []
    conditions << "metas.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(metas.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @metas = Meta.where(conditions.join(' AND ')).order("metas.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /metas/1
  def show
  end

  def new
    @meta = Meta.new
  end

  def edit
  end

  # PATCH/PUT /metas/1
  def update
    respond_to do |format|
      if @meta.update(meta_params)

        @meta.submetas.destroy_all
        c = (@meta.data_inicio.to_date..@meta.data_fim.to_date).map{ |e| e.strftime("%d/%m/%Y")  }
        c.each do |data|
           submeta = Submeta.create(meta_id: @meta.id, data: "#{data}", flg_horas: ((@meta.horas.blank? or @meta.horas.to_i.zero?) ? false : true), horas: @meta.horas, descricao: @meta.descricao )  
           Event.create(title: "#{@meta.horas} #{'horas -' if submeta.flg_horas} #{@meta.nome} - #{@meta.porcentagem}%", color: "red", start: (submeta.data.to_date), end: (submeta.data.to_date+1.day), user_id: current_user.id, submeta_id: submeta.id, description: @meta.descricao)
           submeta = nil   
        end

        format.js {render inline: "Materialize.toast('Atualizado com sucesso!', 4000, 'green')" }
      else
        format.js
      end
    end
  end

  def create
    @meta = Meta.new(meta_params)

      if @meta.save
        c = (@meta.data_inicio.to_date..@meta.data_fim.to_date).map{ |e| e.strftime("%d/%m/%Y")  }
        c.each do |data|
           submeta = Submeta.create(meta_id: @meta.id, data: "#{data}", flg_horas: ((@meta.horas.blank? or @meta.horas.to_i.zero?) ? false : true), horas: @meta.horas, descricao: @meta.descricao )     
           Event.create(title: "#{@meta.horas} horas - #{@meta.nome} - #{@meta.porcentagem}%", color: "red", start: (submeta.data.to_date), end: (submeta.data.to_date+1.day), user_id: current_user.id, submeta_id: submeta.id, description: @meta.descricao)
           submeta = nil
        end
        redirect_to edit_user_meta_path(@meta), notice: "Meta Criado!"
      else
        respond_to do |format|
            format.js
        end
      end
  end

  def destroy
    @meta.destroy
    
    redirect_to request.referrer, notice: "Meta Deletada!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meta
      @meta = Meta.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def meta_params
      params.require(:meta).permit(:nome, :descricao, :publico, :data_inicio, :data_fim, :horas, :user_id )
    end

    def garantir_autorizacao
      authorize! :config,     :metas
    end

end

app/controllers/user/pages_controller.rb
class User::PagesController < User::UserController
  def home
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :image)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :description, :email, :password, :password_confirmation, :current_password, :image)
  end
end

app/controllers/user/servicos_controller.rb
class User::ServicosController < User::UserController

  before_action :set_servico, only: [:show, :edit, :update, :destroy]
  before_action :garantir_autorizacao

  # GET /servicos
  def index
    conditions = []
    conditions << "servicos.id = #{params[:id]}" unless params[:id].blank?
    conditions << "(UPPER(servicos.nome) LIKE '%#{params[:nome]}%')" unless params[:nome].blank?

    @servicos = Servico.where(conditions.join(' AND ')).order("servicos.created_at DESC")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /servicos/1
  def show
  end

  def new
    @servico = Servico.new
  end

  def edit
  end

  # PATCH/PUT /servicos/1
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.js {render inline: "Materialize.toast('Atualizado com sucesso!', 4000, 'green')" }
      else
        format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
      end
    end
  end

  def create
    @servico = Servico.new(servico_params)
      if @servico.save
        redirect_to edit_user_servico_path(@servico), notice: "Serviço Criado!"
      else
        respond_to do |format|
            format.js {render inline: "Materialize.toast('Falha', 4000, 'red')" }
        end
      end
  end

  def destroy
    @servico.destroy
    
    redirect_to request.referrer, notice: "Serviço Deletado!"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def servico_params
      params.require(:servico).permit(:nome, :descricao, :icon, :icon_color, :icon_size)
    end

    def garantir_autorizacao
      authorize! :config,     :servicos
    end

end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
	
  before_action :authenticate_user!
  
  layout 'user'

  def home
  end

  
end

app/controllers/users_controller.rb
class UsersController < PublicController
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/users/_form.html.erb
      <%= form_for [:user, @user], remote: true do |f| %>

      <div id="form_error">
      </div>

      <div class="row">
        <div class="field">
          <div class="input-field col s12 m4 l4">
            <i class="material-icons prefix">account_circle</i>
            <%= f.text_field :nome, autofocus: true, class: "go_next"  %>
            <label for="icon_prefix">Nome / Razão Social</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m4 l4">
            <i class="material-icons prefix">email</i>
            <%= f.text_field :email, class: "go_next"  %>
            <label for="icon_prefix">E-mail</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m4 l4">
            <i class="material-icons prefix">lock</i>
              <%= f.password_field :password, autocomplete: "off" %>
            <label for="icon_prefix">Senha</label>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12 m4">
          <i class="material-icons prefix">folder_shared</i>
          <%= f.text_field :cpf, :onkeypress => "mascara(this, checaCPF)", maxlength: 14, class: "go_next"  %>
          <label for="icon_prefix">CPF</label>
        </div>
        <div class="input-field col s12 m4">
          <i class="material-icons prefix">folder_shared</i>
          <%= f.text_field :cnpj, :onkeypress => "mascara(this, checaCNPJ)", maxlength: 18, class: "go_next"  %>
          <label for="icon_prefix">CNPJ</label>
        </div>
        <div class="input-field col s12 m4">
          <i class="material-icons prefix">folder_shared</i>
          <%= f.text_field :rg, class: "go_next", maxlength: 18 %>
          <label for="icon_prefix">I.E. / RG</label>
        </div>
      </div>


      <div class="row">

        <div class="field">
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">phone</i>
            <%= f.text_field :telefone, :onkeypress => "mascara(this, checaTelefone)", maxlength: 15, class: "go_next" %>
            <label for="icon_prefix">Telefone</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m6">
            <i class="material-icons prefix">phone</i>
            <%= f.text_field :celular, :onkeypress => "mascara(this, checaTelefone)", maxlength: 15, class: "go_next" %>
            <label for="icon_prefix">Celular</label>
          </div>
        </div>
      </div>


      <div class="row">

        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :data_nascimento, :onkeypress => "mascara(this, checaData)", maxlength: 10, class: "go_next" %>
            <label for="icon_prefix">Data de Nascimento</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :nacionalidade, class: "go_next" %>
            <label for="icon_prefix">Nacionalidade</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :sex, class: "go_next" %>
            <label for="icon_prefix">Sexo</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :estado_civil, class: "go_next" %>
            <label for="icon_prefix">Estado Civil</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m12 l4">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :profissao, class: "go_next" %>
            <label for="icon_prefix">Profissão</label>
          </div>
        </div>

        <div class="field">
          <div class="input-field col s12 m12 l12">
            <i class="material-icons prefix">arrow_forward</i>
            <%= f.text_field :location, class: "go_next" %>
            <label for="icon_prefix">Endereço</label>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="switch col s12">
          <div class="title">
            <p>Admin</p>
          </div>
          <label>
            Não
            <%= f.check_box :flg_admin %>
            <span class="lever"></span>
            Sim
          </label>
        </div>
      </div>
      
      <div class="row">
        <div class="input-field col s12">
          <div class="actions">
            <button class="btn blue waves-effect waves-light right" type="submit" name="action">Salvar
              <i class="material-icons right">send</i>
            </button>
          </div>
        </div>
      </div>

      <% end %>






<script type="text/javascript">

  $(document).ready(function() {
    $('select').material_select();
  });
    
</script>

app/views/user/users/_form_success.html.erb
<div class="row">
  <div class="col s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Cadastro realizado com sucesso <span class="badge green white-text"><%= 3 %></span></span>
          <p><%= user.nome %></p>
          <p><%= user.email %></p>
          <p><%= user.celular %></p>
          <p><%= user.categoria.nome unless user.categoria.blank? %></p>
      </div>
      <div class="card-action">
      </div>
    </div>
  </div>
</div>

app/views/user/users/_list.html.erb
<table class="highlight responsive-table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>E-Mail</th>
      <th>Celular</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.nome %></td>
        <td><%= user.email %></td>
        <td><%= user.celular %></td>
        <td>
          <%= link_to "<i class='material-icons prefix'>edit</i>".html_safe, edit_user_user_path(user), class: "btn blue btn-floating" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/users/create.js.erb
<% if @user.errors.any? %>
  $("#form_error").html("<%= j( render '/shared/form_error', object: @user )%>");
  $('html, body').animate({ scrollTop: 0 }, 'slow');
<% end %>

app/views/user/users/edit.html.erb
<div id="user" class="container-fluid">
  <h4 class="title grey-text" style="margin: 0;" ><%= "Editar #{@user.nome}" %></h4><br>
  <div class="layout">
	  <%= render 'form'  %>
  </div>
</div>

app/views/user/users/index.html.erb
<div  style="border: 1px solid #ccc; padding: 15px;">
	<h4 class="title grey-text" style="margin: 0;" ><%= "Usuários" %></h4>
  <br>
	<%= link_to "CRIAR USUÁRIO", new_user_user_path, class: "btn green" %>
	

  <div class="row">
    <form class="col s12">
      <div class="row">
		<div class="input-field col s6 m6 l3">
		  <input id="id" type="text" class="validate">
		  <label class="active" for="id">Código</label>
		</div>
		<div class="input-field col s6 m6 l3">
		  <input id="name" type="text" class="validate">
		  <label class="active" for="name">Nome Completo</label>
		</div>
		<div class="input-field col s6 m6 l3">
		  <input id="email" type="text" class="validate">
		  <label class="active" for="email">E-mail</label>
		</div>
		<div class="input-field col s6 m6 l3">
		<a id="buscar" class="btn blue">Buscar</a>
		</div>
      </div>
    </form>
  </div>

<div class="row">
  <div class="col s12 m12 l12">
    <div id="user_list">
      <%= render 'list' %>
    </div>
  </div>
</div>

</div>

<script type="text/javascript">

  $(function($) {

    $("#buscar").click(function() {
      if( $(this).prop('value') != "" ) {
        var email = $("#email").prop('value');
        var id = $("#id").prop('value');
        var name = $("#name").prop('value');
        att_index(id, name, email);
      }
    });
  });



</script>

<script type="text/javascript">
  
function att_index(id, name, email){

    $.ajax({
      url: "/user/users",
      method: "GET",
      dataType: "script",
      data: {
      	'id': 			id,
        'nome': 		name,
        'email': 		email
      },
    });

}
</script>

<script type="text/javascript">
  $("input").keyup(function() {
    $(this).val($(this).val().toUpperCase());
  });
</script>

app/views/user/users/index.js.erb
$("#user_list").html("<%= j( render 'list' )%>");

app/views/user/users/new.html.erb
<div id="user" class="container-fluid">
  <h4 class="grey-text" style="margin: 0;" ><%= "Novo Usuário" %></h4>
  <br>
  <div class="layout">
	  <%= render 'form'  %>
  </div>
</div>

app/views/user/users/update.js.erb
<% if @user.errors.any? %>
  $("#form_error").html("<%= j( render '/shared/form_error', object: @user )%>");
  $('html, body').animate({ scrollTop: 0 }, 'slow');
<% end %>